// pwd module — 9a ops.
//
// Two flows:
//
//  - pwd.fill (extension-initiated): on focus of <input type="password">,
//    a content script messages the background which calls
//    qdistroDispatcher.request("pwd.fill", {url, username?, intent_token}).
//    Bridge replies with `{credentials: [...]}` or `{error: ...}`.
//
//  - pwd.save (extension-initiated): on form submit with new
//    credentials, same path with `{url, username, password, intent_token}`.
//
// The bridge-initiated direction is not used for pwd: the daemon
// never pushes a fill — fills are always user-initiated.
//
// Intent token is generated by intent.js; we accept it as opaque
// here and forward it to the bridge.
//
// @ts-check
(function (root) {
  "use strict";
  const dispatcher = root.qdistroDispatcher;

  async function fill(url, username, intentToken) {
    return await dispatcher.request("pwd.fill", {
      url, username: username || null, intent_token: intentToken,
    });
  }

  async function save(url, username, password, intentToken) {
    return await dispatcher.request("pwd.save", {
      url, username, password, intent_token: intentToken,
    });
  }

  // No inbound handlers — pwd is purely extension-initiated.
  root.qdistroPwd = { fill, save };
})(typeof self !== "undefined" ? self : globalThis);
